### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by titihoho** [peng-xiao-shuai/vite-vue-admin#4]
点击菜单列表 无响应 报错
下午5:14:56 [vite] Internal server error: v-model cannot be used on a prop, because local prop bindings are not writable.
Use a v-bind binding combined with a v-on listener that emits update:x event instead.
  Plugin: vite:vue
  File: C:/Users/Administrator/Desktop/vite-vue-admin/vite/src/views/authority/menu/components/update.vue
  2  |    <el-drawer
  3  |      :title="currentFrom.id ? '修改' : '添加'"
  4  |      v-model="dialog"
     |                ^
  5  |  
  6  |      @close="close"
      at createCompilerError (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:19:19)
      at Object.transformModel (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:5393:25)
      at transformModel (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vue\compiler-dom\dist\compiler-dom.cjs.js:2536:37)
      at buildProps (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:4781:48)
      at Array.postTransformElement (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:4378:38)
      at traverseNode (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2225:19)
      at traverseChildren (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2167:9)
      at traverseNode (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2218:13)
      at transform (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:2100:5)
      at Object.baseCompile (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vue\compiler-core\dist\compiler-core.cjs.js:5716:5)
      at Object.compile (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vue\compiler-dom\dist\compiler-dom.cjs.js:3105:25)
      at doCompileTemplate (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:3235:49)
      at Object.compileTemplate (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:3208:16)
      at compile (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vitejs\plugin-vue\dist\index.js:4196:27)
      at transformTemplateInMain (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vitejs\plugin-vue\dist\index.js:4189:18)
      at genTemplateCode (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vitejs\plugin-vue\dist\index.js:4551:12)
      at transformMain (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\@vitejs\plugin-vue\dist\index.js:4477:55)
      at async Object.transform (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\vite\dist\node\chunks\dep-689425f3.js:39317:30)
      at async doTransform (C:\Users\Administrator\Desktop\vite-vue-admin\vite\node_modules\vite\dist\node\chunks\dep-689425f3.js:50043:29) (x2)

**Comment by titihoho** [comment]
v-model="dialog"

**Comment by peng-xiao-shuai** [comment]
能否提供仓库地址，方便我们复现。

**Comment by titihoho** [comment]
没事了，处理好了

**Comment by sherry-wni** [comment]
大佬，有没有交流群啊

**Comment by peng-xiao-shuai** [comment]
> 大佬，有没有交流群啊

很遗憾并没有学习交流群，如果你学习该项目中遇到什么问题的话可以直接联系我，我觉得对于该项目问题我应该比交流群更清楚。如果真的存在什么问题我很乐意为你解答。
